name: labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@master
        with:
          GITHUB_TOKEN: ${{ secrets.the_token }}
          xs_max_size: '10'
          s_max_size: '20'
          m_max_size: '30'
          l_max_size: '40'
          fail_if_xl: 'false'

# https://github.com/marketplace/actions/pull-request-size-labeler
