name: quarto-setup

on: 
  push:
    branches: none

jobs:          
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/renv:v3
    steps:
     - uses: actions/checkout@v1
       
       name: Setting Up Renv Libraries
     - run: |
          sudo apt-get update
          sudo apt-get install tree
          echo "SHOW FILES"
          cd /__w/quarto-actions/quarto-actions/
          pwd
          ls -la
          Rscript -e 'renv::activate()'
          Rscript -e 'renv::restore()'
  
  
  #        jpgomezz/quarto:final
  #        Rscript -e 'install.packages("renv")'
  #        Rscript -e 'install.packages("yaml")'
  #        Rscript -e 'renv::activate()'
  #        Rscript -e 'renv::restore()'
  #        Rscript -e 'renv::install()'
  #        Rscript -e 'renv::install("memoise")'
          

          
    
    
    #      chmod +x Rlibraries.sh
    #      ./Rlibraries.sh
          
       name: Rendering Files
     - run: |
          pwd
          cd /__w/quarto-actions/quarto-actions/
          quarto render --to html
          Rscript -e 'renv::snapshot()'
          echo "SHOW RENV FILES"
          pwd
          ls -la
          tree public/markdown/
          echo "SHOWING renv.lock CONTENT"
          cat renv.lock
          
          
     - uses: actions/upload-artifact@master
       with:
        name: my-artifact
        path: public/markdown/

#  sftp-transfer:
#    needs: quarto-linux
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout repository content
#        uses: actions/checkout@master
#      - uses: actions/download-artifact@master
#        with:
#         name: my-artifact
#         path: public/markdown/
#      - run: | 
#          echo CHECKING ARTIFACT
#          ls -la /home/runner/work/quarto-actions/quarto-actions/public/markdown/
          
          
 #     - name: Preparing Environment
 #       run: |   
 #         mkdir -p ${{ secrets.SSH_PATH }}
 #         touch /home/runner/.ssh/known_hosts
 #         touch ${{ secrets.SSH_CONFIG_PATH }}
 #         echo "${{ secrets.SSH_CONFIG }}" >> ${{ secrets.SSH_CONFIG_PATH }}
 #         echo "${{ secrets.PRIVATEKEY }}" > "/home/runner/.ssh/id_rsa"    
 #         echo "${{ secrets.PUBLICKEY }}" > "/home/runner/.ssh/id_rsa.pub"      
 #         echo "${{ secrets.KNOWN_HOSTS }}" > "/home/runner/.ssh/known_hosts"
 #         chmod 700 "/home/runner/.ssh/"
 #         chmod 644 "/home/runner/.ssh/known_hosts"
 #         chmod 600 "/home/runner/.ssh/id_rsa"
 #         chmod 644 "/home/runner/.ssh/id_rsa.pub"
 #         chmod 600 "/home/runner/.ssh/config"
     
 #     - name: Installing Terminus
 #       uses: kopepasah/setup-pantheon-terminus@master
 #       with:
 #         pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      
 #     - name: Development mode to SFTP
 #       if: success()
 #       run: |
 #         terminus site:list
 #         terminus connection:set jptest1.dev sftp
 #        sleep 60
     
 #     - name: Transferring files to Pantheon
 #       run: |
 #         sftp -oPort=2222 dev.6ea2702b-ed4d-4196-b545-10c1de13b528@appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in <<END
 #         put -r /home/runner/work/quarto-actions/quarto-actions/public/markdown/* /files/
          
 #     - name: Development mode back to Git
 #       if: success()
 #       run: |
 #         terminus site:list
 #         terminus connection:set jptest1.dev git
