name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quarto:final
    steps:            
      - uses: actions/checkout@v2
      - run: |
          echo STARTING WITH THE PROJECT
          


      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
      - name: Installing Terminus
        uses: kopepasah/setup-pantheon-terminus@master
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Listing Sites
        if: success()
        run: |
          terminus site:list




    
      #### STARTING WITH THE PROJECT FULL RUN
      #    sudo apt-get update
      #    sudo apt-get install tree
      #    echo STARTING WITH THE PROJECT
      #    cd /__w/quarto-actions/quarto-actions/
      #    quarto render --to html
      #    tree public/markdown/
      
   
   
   
   
   
   
 
