name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup
      - uses: r-lib/actions/setup-r@v2
      - run: |
          sudo R --vanilla <<EOF 
          install.packages("jsonlite", repos = 'https://cran.r-project.org')
          install.packages("rmarkdown", repos = 'https://cran.r-project.org')
          install.packages("ggplot2", repos = 'https://cran.r-project.org')
          install.packages("dplyr", repos = 'https://cran.r-project.org')
          q()
          EOF
          quarto create-project myproject; cd myproject; rm _quarto.yml
          echo list my files 
          cd ~
          ls -l
#          mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
#          mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
#          quarto render --to html   
