name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version
          
          
  
 
   #sudo apt install snapd
  #sudo snap install gh
 
#       - uses: r-lib/actions/setup-r@v2
#  - uses: ./setup
 #         sudo R --vanilla <<EOF 
 #         install.packages("jsonlite", repos = 'https://cran.r-project.org')
 #         install.packages("rmarkdown", repos = 'https://cran.r-project.org')
 #         install.packages("ggplot2", repos = 'https://cran.r-project.org')
 #         install.packages("dplyr", repos = 'https://cran.r-project.org')
 #         q()
 #         EOF
 #         quarto create-project myproject; cd myproject; rm _quarto.yml
 #         echo list my files directories
 #         mv ~/work/quarto-actions/quarto-actions/_quarto.yml ~/work/quarto-actions/quarto-actions/myproject/_quarto.yml
 #         mv ~/work/quarto-actions/quarto-actions/markdown ~/work/quarto-actions/quarto-actions/myproject/markdown
 #         quarto render --to html
 #         tree ~/work/quarto-actions/quarto-actions


