name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quatro:seis
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          quarto --version
          sudo apt-get install tree
          sudo apt-get install r-base r-base-dev -y
          echo PERFORMING LIBRARIES ADJUSTMENT
          cd /opt/R/4.2.1/lib/R/
          rm -rf library
          ln -s /usr/local/lib/R/site-library library
          echo SHOW SITE LIBRARIES TREE
          tree /opt/R/4.2.1/lib/R/library
          echo STARTING WITH THE PROJECT
          cd /__w/quarto-actions/quarto-actions/
          sudo mkdir proyectito; cd proyectito
          quarto create-project myproject; cd myproject; rm _quarto.yml
          mv /__w/quarto-actions/quarto-actions/_quarto.yml  /__w/quarto-actions/quarto-actions/proyectito/myproject
          mv /__w/quarto-actions/quarto-actions/markdown /__w/quarto-actions/quarto-actions/proyectito/myproject/markdown  
          sudo R --vanilla <<EOF 
          install.packages("jsonlite", repos = 'https://cran.r-project.org')
          q()
          EOF
      #  quarto render --to html 
      #  echo FULL TREE
      #  tree /__w/quarto-actions/quarto-actions/
      #  echo LIST quarto-actions FOLDER
      #  ls -l /__w/quarto-actions/quarto-actions/
