name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quatro:seis
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          quarto --version
          quarto create-project myproject; cd myproject; rm _quarto.yml
          echo DIRECTORIES
          pwd
          ls -l



#          quarto create-project myproject; cd myproject; rm _quarto.yml
#          mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
#          mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
#          quarto render --to html  
