name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quatro:seis
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          sudo apt-get install tree
          quarto --version
          quarto create-project myproject; cd myproject; rm _quarto.yml 
          echo FULL TREE
          tree /__w/quarto-actions/quarto-actions/
          echo LIST quarto-actions FOLDER
          ls - /__w/quarto-actions/quarto-actions/


    #      mv /__w/quarto-actions/quarto-actions/_quarto.yml /__w/quarto-actions/quarto-actions/myproject/myproyect/_quarto.yml
    #      mv /__w/quarto-actions/quarto-actions/markdown /__w/quarto-actions/quarto-actions/myproject/markdown
    #      quarto render --to html 
