name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quarto:final            
    steps:             
     - uses: actions/checkout@v2
       name: Render files
     - run: |
        echo DIRECTORIES CONTAINER
        cd /
        ls -la
        echo changing directories looking for repo files
        cd __w
        pwd
        ls -la
     
  job2-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@v2
      - run: | 
          echo PRINT ROOT DIRECTORIES RUNNER
          cd /
          ls -la
     
     
     
     
     
     # WORKING ONE!!!!!!!
     #     echo Making listing home files
     #     mkdir -p ${{ secrets.SSH_PATH }}
     #     touch /home/runner/.ssh/known_hosts
     #     touch ${{ secrets.SSH_CONFIG_PATH }}
     #     echo "${{ secrets.SSH_CONFIG }}" >> ${{ secrets.SSH_CONFIG_PATH }}
     #     echo "${{ secrets.PRIVATEKEY }}" > "/home/runner/.ssh/id_rsa"    
     #     echo "${{ secrets.PUBLICKEY }}" > "/home/runner/.ssh/id_rsa.pub"      
     #     echo "${{ secrets.KNOWN_HOSTS }}" > "/home/runner/.ssh/known_hosts"
     #     chmod 700 "/home/runner/.ssh/"
     #     chmod 644 "/home/runner/.ssh/known_hosts"
     #     chmod 600 "/home/runner/.ssh/id_rsa"
     #     chmod 644 "/home/runner/.ssh/id_rsa.pub"
     #     chmod 600 "/home/runner/.ssh/config"
     #     echo SSH DIRECTORIES STATUS CHECK
     #     cd /home/runner/.ssh/
     #     pwd
     #     ls -la
     #     sftp -oPort=2222 dev.6ea2702b-ed4d-4196-b545-10c1de13b528@appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in

# sftp -o StrictHostKeyChecking=no appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in;

#=====================

    # WORKING
    
 #       - name: Prepare Environment
 #     env:
 #        SSH_KEY_PRIVATE: ${{ secrets.PRIVATEKEY }}
 #        SSH_KEY_PUBLIC: ${{ secrets.PUBLICKEY }}
 #        SSH_PATH: /home/runner/.ssh
 #        KNOWN_HOSTS_PATH: /home/runner/.ssh/known_hosts
 #        SSH_KEY_PRIVATE_PATH: /home/runner/.ssh/id_rsa
 #        SSH_KEY_PUBLIC_PATH: /home/runner/.ssh/id_rsa.pub
 #        SSH_CONFIG_PATH: /home/runner/.ssh/config
 #        SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
 #        KNOWN_HOST_URL: ${{ secrets.KNOWN_HOST_URL }}
 #        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
 #     run: |
 #        echo show CD ~
 #        cd ~
 #        pwd
 #        ls -la
 #        mkdir -p $SSH_PATH
 #        touch $KNOWN_HOSTS_PATH
 #        touch $SSH_CONFIG
 #        echo "$SSH_CONFIG" >> "$SSH_CONFIG_PATH"
 #        echo "$SSH_KEY_PRIVATE" > "$SSH_KEY_PRIVATE_PATH"
 #        echo "$SSH_KEY_PUBLIC" > "$SSH_KEY_PUBLIC_PATH"
 #        echo "$KNOWN_HOSTS" > "$KNOWN_HOSTS_PATH"
 #        chmod 700 "$SSH_PATH"
 #        chmod 644 "$KNOWN_HOSTS_PATH"
 #        chmod 600 "$SSH_KEY_PRIVATE_PATH"
 #        chmod 644 "$SSH_KEY_PUBLIC_PATH"
 #        chmod 600 "$SSH_CONFIG_PATH"
 #        echo STATUS CHECK
 #        cd ~/.ssh
 #        pwd
 #        ls -la
 #        sftp -oPort=2222 dev.6ea2702b-ed4d-4196-b545-10c1de13b528@appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in
    
    
    
         
      # ENV=dev;
      # export SITE=6ea2702b-ed4d-4196-b545-10c1de13b528;




# ORIGIGIGI
#    - uses: actions/checkout@v2
#    - run: |
#        echo WHO AM I
#        whoami
#        echo PRINT HOME DIRECTORY
#        cd ~/
#        pwd
#        ls -la


 #     - name: Installing PHP
 #       uses: shivammathur/setup-php@master
 #       with:
 #         php-version: '8.1'
 #     - name: Installing Terminus
 #       uses: kopepasah/setup-pantheon-terminus@master
 #       with:
 #         pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
 #     - name: Listing Sites
 #       if: success()
 #       run: |
 #         terminus site:list



    
      #### STARTING WITH THE PROJECT FULL RUN
      #    sudo apt-get update
      #    sudo apt-get install tree
      #    echo STARTING WITH THE PROJECT
      #    cd /__w/quarto-actions/quarto-actions/
      #    quarto render --to html
      #    tree public/markdown/
      
   
   
   
   
   
   
 
