name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quatro:cuatro
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          sudo apt-get update -y; sudo apt-get upgrade -y; sudo apt-get install r-base r-base-dev
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+; sudo apt update; sudo apt-get install -y r-cran-jsonlite
          sudo R --vanilla <<EOF 
          install.packages("jsonlite", repos = 'https://cran.r-project.org')
          install.packages("rmarkdown", repos = 'https://cran.r-project.org')
          install.packages("ggplot2", repos = 'https://cran.r-project.org')
          install.packages("dplyr", repos = 'https://cran.r-project.org')
          q()
          EOF
          quarto create-project myproject; cd myproject; rm _quarto.yml
          mv /__w/quarto-actions/quarto-actions/_quarto.yml /__w/quarto-actions/quarto-actions//myproject/_quarto.yml
          mv /__w/quarto-actions/quarto-actions/markdown /__w/quarto-actions/quarto-actions/myproject/markdown
          quarto render --to html
          echo list my files directories
          tree /__w/quarto-actions/quarto-actions/


