name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quatro:seis
    steps:            
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          quarto --version
          sudo R --vanilla <<EOF
          install.packages("rmarkdown", repos = 'https://cran.r-project.org')
          install.packages("jsonlite", repos = 'https://cran.r-project.org')
          q()
          EOF 
          sudo apt-get install tree
          sudo mkdir proyectito; cd proyectito
          quarto create-project myproject; cd myproject; rm _quarto.yml
          mv /__w/quarto-actions/quarto-actions/_quarto.yml  /__w/quarto-actions/quarto-actions/proyectito/myproject
          mv /__w/quarto-actions/quarto-actions/markdown /__w/quarto-actions/quarto-actions/proyectito/myproject/markdown       
          quarto render --to html 
          echo FULL TREE
          tree /__w/quarto-actions/quarto-actions/
          echo LIST quarto-actions FOLDER
          ls -l /__w/quarto-actions/quarto-actions/



