name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quarto:final
    steps:            
      - uses: actions/checkout@v2
      - run: |
          echo STARTING WITH THE PROJECT
 
      - name: Prepare Environment
        env:
         SSH_KEY_PUBLIC: ${{ secrets.PUBLICKEY }}
         SH_KEY_PRIVATE: ${{ secrets.PRIVATEKEY }}
         SSH_PATH: /github/home/.ssh
         KNOWN_HOSTS_PATH: /github/home/.ssh/known_hosts
         SSH_KEY_PRIVATE_PATH: /github/home/.ssh/id_rsa
         SSH_KEY_PUBLIC_PATH: /github/home/.ssh/id_rsa.pub
        run:
          cd ~/
          pwd
          ls -la
          mkdir .ssh
          ls -la
 #         echo "$SSH_KEY_PRIVATE" > "$SSH_KEY_PRIVATE_PATH"
 #         echo "$SSH_KEY_PUBLIC" > "$SSH_KEY_PUBLIC_PATH"
 #         echo .ssh cd to and list
 #         cd .ssh
 #         pwd
 #         ls -la
  #       ssh -T appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in
  #       sftp -oPort=2222 dev.6ea2702b-ed4d-4196-b545-10c1de13b528@appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in
          
          


 #     - name: Installing PHP
 #       uses: shivammathur/setup-php@master
 #       with:
 #         php-version: '8.1'
 #     - name: Installing Terminus
 #       uses: kopepasah/setup-pantheon-terminus@master
 #       with:
 #         pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
 #     - name: Listing Sites
 #       if: success()
 #       run: |
 #         terminus site:list




    
      #### STARTING WITH THE PROJECT FULL RUN
      #    sudo apt-get update
      #    sudo apt-get install tree
      #    echo STARTING WITH THE PROJECT
      #    cd /__w/quarto-actions/quarto-actions/
      #    quarto render --to html
      #    tree public/markdown/
      
   
   
   
   
   
   
 
