name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./quarto-actions/setup
      - uses: r-lib/actions/setup-r@v2
      - run: |
          quarto create-project myproject; 
          echo list my files 
          cd ~
          ls -l
