name: quarto-setup

on: 
  push:
    branches: main

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quarto:final
    steps:            
      - uses: actions/checkout@v2
      - run: |
          echo STARTING WITH THE PROJECT


      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
      - name: Installing Terminus
        uses: kopepasah/setup-pantheon-terminus@master
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Listing Sites
        if: success()
        run: |
          terminus site:list
          terminus self:plugin:install terminus-rsync-plugin
          auth:whoami







      
      
      #   terminus site:list
      #   terminus self:plugin:install terminus-rsync-plugin
      #   terminus help remote:rsync
      #   terminus rsync /__w/quarto-actions/quarto-actions/ jptest1.dev:files
         

      
      
      
      

      
    
    
    
    
      #### STARTING WITH THE PROJECT FULL RUN
      #    sudo apt-get update
      #    sudo apt-get install tree
      #    echo STARTING WITH THE PROJECT
      #    cd /__w/quarto-actions/quarto-actions/
      #    quarto render --to html
      #    tree public/markdown/
      
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
  # PREVIOUS WORKING BUILD 
  #        sudo apt-get update
  #        sudo apt-get install tree
  #        echo STARTING WITH THE PROJECT
  #        cd /__w/quarto-actions/quarto-actions/
  #        sudo mkdir proyectito; cd proyectito; quarto create-project myproject; cd myproject; rm _quarto.yml
  #        mv /__w/quarto-actions/quarto-actions/_quarto.yml  /__w/quarto-actions/quarto-actions/proyectito/myproject
  #        mv /__w/quarto-actions/quarto-actions/markdown /__w/quarto-actions/quarto-actions/proyectito/myproject/markdown  
  #        echo RENDERING WITH QUARTO
  #        quarto render --to html 
  #        tree public/markdown/
  # UP TO HERE - CROSSREF WARININGS
   
 
